<a href="https://colab.research.google.com/github/Kasterli/bigdata/blob/main/big_data_pw3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

np.random.seed(42)

n = 1000000

data = np.column_stack( [
    np.arange(1, n+1),
    np.random.randint(1, 1001, n),
    np.random.randint(500, 100000, n),
    np.random.randint(1, 10, n),
    np.random.randint(1, 6, n)
])

print('Деректер жиынының өлшемі', data.shape)
print('Алғашқы он жазба: ', data[:10])
print('Соңғы он жазба: ', data[-10:])

Деректер жиынының өлшемі (1000000, 5)
Алғашқы он жазба:  [[    1   103 67621     8     4]
 [    2   436 19204     5     3]
 [    3   861 78245     9     5]
 [    4   271 28269     3     2]
 [    5   107 93611     7     1]
 [    6    72 62202     1     1]
 [    7   701 32758     6     1]
 [    8    21  2105     9     5]
 [    9   615 74759     2     2]
 [   10   122  8257     4     1]]
Соңғы он жазба:  [[ 999991     703   71732       6       5]
 [ 999992     411   24031       8       1]
 [ 999993     431   10839       5       1]
 [ 999994     123   46004       4       2]
 [ 999995     582   59805       1       4]
 [ 999996      91   73926       3       5]
 [ 999997     318    9906       5       2]
 [ 999998     479    7105       9       5]
 [ 999999      21   66427       3       3]
 [1000000     901    3007       9       2]]


In [5]:
selected_data = data[100000:100010]
print(selected_data)

[[100001    714  50166      8      3]
 [100002    384  92974      7      5]
 [100003    428  18938      9      4]
 [100004    158  48814      3      2]
 [100005    745  35719      3      2]
 [100006    627  22667      1      3]
 [100007    225  53019      3      1]
 [100008    557  36139      6      4]
 [100009    729  36277      5      5]
 [100010    999  32586      1      4]]


In [6]:
selected_columns = data[:, [0,1]]
print(selected_columns)

[[      1     103]
 [      2     436]
 [      3     861]
 ...
 [ 999998     479]
 [ 999999      21]
 [1000000     901]]


In [7]:
print('Ең аз сатып алу сомасы', np.min(data[:, 0]))
print('Ең көп сату алу сомасы', np.max(data[:, 0]))

Ең аз сатып алу сомасы 1
Ең көп сату алу сомасы 1000000


In [9]:
average_amount = np.mean(data[:, 0])
print('Орташа сатып алу сомасы: ', average_amount)

Орташа сатып алу сомасы:  500000.5


In [17]:
import numpy as np

np.random.seed(42)

n = 2000000

data = np.column_stack( [
    np.arange(1, n+1),
    np.random.randint(1, 1001, n),
    np.random.randint(500, 100000, n),
    np.random.randint(1, 10, n),
    np.random.randint(1, 6, n)
])

In [19]:
print('Алғашқы 1000 жазба:', data[:1000])
print()
print('Соңғы 5000 жазба:', data[-5000:])
print()
print('2-5 бағандар:', data[:, 1:6])
print()
print('Әр 10-жазба:', data[::10, :])
print()
print('Баға, жеңілдік, салық бағандар', data[:, [2,3,4]])
print()
data_2= data[1000000:2000000]
print('Үзінді жаңа деректер жиыны:', data_2)


Алғашқы 1000 жазба: [[    1   103 26287     8     2]
 [    2   436 23143     4     4]
 [    3   861 40406     7     5]
 ...
 [  998   798 20869     3     4]
 [  999   242 56770     3     3]
 [ 1000   251 97892     5     1]]

Соңғы 5000 жазба: [[1995001     731   73169       5       5]
 [1995002     390   80732       5       3]
 [1995003     175   56859       3       5]
 ...
 [1999998     158   74740       3       1]
 [1999999     582   66241       6       5]
 [2000000     283   68609       7       2]]

2-5 бағандар: [[  103 26287     8     2]
 [  436 23143     4     4]
 [  861 40406     7     5]
 ...
 [  158 74740     3     1]
 [  582 66241     6     5]
 [  283 68609     7     2]]

Әр 10-жазба: [[      1     103   26287       8       2]
 [     11     467   10068       1       4]
 [     21     662   62571       8       3]
 ...
 [1999971     522   51580       4       4]
 [1999981     580   26898       8       1]
 [1999991     779   53659       2       1]]

Баға, жеңілдік, салық бағандар 

In [20]:
import numpy as np
# Сатып алу сомалары
data = np.array([
    5000, 7000, 8000, 6000, 9000,
    7500, 8500, 6500, 10000, 500000
])
# Орташа мән
mean = np.mean(data)
# Стандартты ауытқу
std = np.std(data)
# Z-score есептеу
z_scores = (data - mean) / std
# Аномалияларды анықтау
anomalies = data[np.abs(z_scores) > 2]
print("Орташа мән:", mean)
print("Z-score:", z_scores)
print("Аномалиялар:", anomalies)


Орташа мән: 56750.0
Z-score: [-0.35023816 -0.33670239 -0.3299345  -0.34347028 -0.32316662 -0.33331845
 -0.32655056 -0.34008633 -0.31639873  2.99986602]
Аномалиялар: [500000]


In [21]:
anomalies= data[np.abs(z_scores)>2]
print('Анықталған аномалиялар', anomalies)

Анықталған аномалиялар [500000]


In [24]:
indices = np.where(np.abs(z_scores)>2)[0]

print('Аномалия индектері: ', indices)
print('Аномалия мәндері: ', data[indices])

Аномалия индектері:  [9]
Аномалия мәндері:  [500000]


In [25]:
clean_data = data[np.abs(z_scores)<=2]

new_mean = np.mean(clean_data)

print('Бастапқы орташа мән: ', np.mean(data))
print('Аномалиясыз орташа мән: ', new_mean)

Бастапқы орташа мән:  56750.0
Аномалиясыз орташа мән:  7500.0


In [26]:
print('Аномалияға дейінгі орташа мән: ', np.mean(data))
print('Аномалиядан кейінгі орташа мән: ', np.mean(clean_data))

Аномалияға дейінгі орташа мән:  56750.0
Аномалиядан кейінгі орташа мән:  7500.0
